name: 'Terraform GitHub Actions'
on:
  pull_request:
    branches:
      - master
  push:    

jobs:
  fmt:
    name: 'terraform fmt'
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: hashicorp/setup-terraform@v1

     - name: Terraform fmt
       id: fmt
       run: cd terraform && terraform fmt -check
       continue-on-error: false
  init:
    name: 'terraform init'
    runs-on: ubuntu-latest
    steps:
     - uses: hashicorp/setup-terraform@v1
     - name: Terraform Init
       id: init
       run: cd terraform && terraform init

  validate:
    name: 'terraform validate'
    runs-on: ubuntu-latest
    steps:
     - uses: hashicorp/setup-terraform@v1
     - name: Terraform Validate
       id: validate
       run: cd terraform && terraform validate -no-color

#     - name: Terraform Plan
#       id: plan
#       run: cd terraform &&  terraform plan -no-color
#       continue-on-error: false
